# -*- mode: ruby -*-
# vi: set ft=ruby :
# Contains basic environment for creating VMs

VAGRANT_VERSION="2"
Vagrant.configure(VAGRANT_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.synced_folder ".", "/vagrant"
    #config.vm.network :public_network, ip: "192.168.99.101"
    config.vm.provision "shell", path: "../script/install_docker.sh"
    #config.vm.provision "shell", path: "../script/install_java8.sh"
    #config.vm.provision "shell", path: "../script/install_zookeeper.sh"
    #config.vm.network :public_network, bridge: "en1: Wi-Fi (AirPort)"
    config.vm.boot_timeout = 600
    config.vm.provider "virtualbox" do |v|
        v.name = "docker-basebox"
        v.memory = 512
        v.cpus = 1
    end
end
